name: frontend-app-stack

# Define services
services:
  frontend-app:
    image: amira100/frontend-session18  # Build the image from the current directory
    container_name: frontend-app  # Name of the container
    ports:
      - '3000:80'  # Map port 3000 on the host to port 80 in the container
    networks:
      - frontend-app-network
        # Connect to the defined network

# Define networks
networks:
  frontend-app-network:
    driver: bridge  # Use bridge networking for container communication

# Manual build command (for reference):
# docker build -t assidiwassimdev/frontend-app:latest --build-arg API_URL=https://api.lebondeveloppeur.net/api .
